/* PRENEURA 6.7 — Transaction Operator shared grace decision inbox. */
(function(){
  'use strict';
  if(typeof app==='undefined'||typeof P==='undefined')return;
  function G(){app.fx.lockGrace67=app.fx.lockGrace67||{shortMinutes:15,extendedHours:24,records:[]};app.fx.lockGrace67.records=Array.isArray(app.fx.lockGrace67.records)?app.fx.lockGrace67.records:[];return app.fx.lockGrace67}
  function E(v){try{return typeof fxEsc==='function'?fxEsc(v):String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}catch(_){return String(v==null?'':v)}}
  function R(){try{if(typeof render==='function')render()}catch(_){}}
  function T(v){try{if(typeof toast==='function')toast(v)}catch(_){}}
  function A(type,ref,detail,actor){try{if(typeof fxAudit==='function')fxAudit(type,ref,detail,actor)}catch(_){}}
  function rec(id){return G().records.find(function(x){return x.id===id})||null}
  function activeRows(){return G().records.filter(function(r){return r&&['EXTENSION_REQUESTED','SHORT_ACTIVE','EXPIRED','EXTENDED_24H'].includes(r.status)}).sort(function(a,b){if(a.status==='EXTENSION_REQUESTED'&&b.status!=='EXTENSION_REQUESTED')return -1;if(b.status==='EXTENSION_REQUESTED'&&a.status!=='EXTENSION_REQUESTED')return 1;return String(b.createdAt||'').localeCompare(String(a.createdAt||''))})}
  function left(r){if(!r||!r.expiresAt)return 0;return Math.max(0,new Date(r.expiresAt).getTime()-Date.now())}
  function clock(v){v=Math.floor(Math.max(0,v)/1000);var h=Math.floor(v/3600),m=Math.floor((v%3600)/60),s=v%60;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
  function escJs(v){return String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
  window.p67ApprovePendingGrace=function(id){var r=rec(id);if(!r||r.status!=='EXTENSION_REQUESTED'){T('This extension request is no longer pending.');return}var at=Date.now();r.status='EXTENDED_24H';r.type='EXTENDED_24H';r.approvedAt=new Date(at).toISOString();r.expiresAt=new Date(at+24*3600000).toISOString();r.decision={state:'APPROVED',by:'Transaction Operator',at:r.approvedAt};A('UNIT_LOCK_24H_EXTENSION_APPROVED',r.lockId,r.buyer+' • unit #'+r.unit+' • 24h','TRANSACTION_OPERATOR');T('24-hour extended grace approved for '+r.buyer+'.');R()};
  window.p67RejectPendingGrace=function(id){var r=rec(id);if(!r||r.status!=='EXTENSION_REQUESTED'){T('This extension request is no longer pending.');return}var reason=(prompt('Reason for rejecting the extension','Requirements must be completed within the current grace period.')||'Rejected').trim();r.decision={state:'REJECTED',by:'Transaction Operator',at:new Date().toISOString(),reason:reason};r.status=left(r)>0?'SHORT_ACTIVE':'EXPIRED';A('UNIT_LOCK_24H_EXTENSION_REJECTED',r.lockId,reason,'TRANSACTION_OPERATOR');T('Extended grace request rejected.');R()};
  window.p67GrantOfflineGraceById=function(id){var r=rec(id);if(!r||r.channel!=='SALES_CENTER'||!['SHORT_ACTIVE','EXPIRED'].includes(r.status)){T('This Offline grace record is not eligible for a paperwork exception.');return}var reason=(prompt('Reason for 24-hour paperwork exception','Buyer must complete outstanding physical paperwork.')||'').trim();if(!reason)return;var at=Date.now();r.status='EXTENDED_24H';r.type='EXTENDED_24H';r.request={reason:reason,requestedAt:new Date(at).toISOString(),requestedBy:'Transaction Operator • Offline exception'};r.approvedAt=new Date(at).toISOString();r.expiresAt=new Date(at+24*3600000).toISOString();r.decision={state:'APPROVED',by:'Transaction Operator',at:r.approvedAt,reason:reason};A('UNIT_LOCK_24H_PAPERWORK_EXCEPTION_GRANTED',r.lockId,r.buyer+' • '+reason,'TRANSACTION_OPERATOR');T('24-hour paperwork exception granted for '+r.buyer+'.');R()};
  function inbox(){var rows=activeRows(),pending=rows.filter(function(r){return r.status==='EXTENSION_REQUESTED'}).length,offline=rows.filter(function(r){return r.channel==='SALES_CENTER'&&['SHORT_ACTIVE','EXPIRED'].includes(r.status)}).length;if(!rows.length)return '<div class="p67g-shell"><div class="p67g-empty">No active unit-lock grace decisions are waiting for Transaction Operations.</div></div>';return '<div class="p67g-shell"><section class="p67g-card"><div class="p67g-head"><div><small>TRANSACTION OPERATOR • GRACE DECISION INBOX</small><h4>Unit-lock grace approvals across all buyers</h4><p>This inbox is independent of whichever transaction record is currently open. Online extension requests and Offline paperwork exceptions remain visible until a Transaction Operator decides them.</p></div><span class="p67g-badge '+(pending?'warn':'')+'">'+pending+' REQUESTED • '+offline+' OFFLINE EXCEPTION ELIGIBLE</span></div><div class="p67g-tablewrap"><table class="p67g-table"><tr><th>Buyer</th><th>Unit / lock</th><th>Channel</th><th>Status</th><th>Remaining</th><th>Reason</th><th>Transaction Operator action</th></tr>'+rows.map(function(r){var actions='';if(r.status==='EXTENSION_REQUESTED')actions='<button class="green" onclick="p67ApprovePendingGrace(\''+escJs(r.id)+'\')">Approve 24h Extension</button> <button class="danger" onclick="p67RejectPendingGrace(\''+escJs(r.id)+'\')">Reject Extension</button>';else if(r.channel==='SALES_CENTER'&&['SHORT_ACTIVE','EXPIRED'].includes(r.status))actions='<button class="warn" onclick="p67GrantOfflineGraceById(\''+escJs(r.id)+'\')">Grant 24h Paperwork Exception</button>';else if(r.status==='EXTENDED_24H')actions='<span class="p67g-badge ok">APPROVED 24H</span>';else actions='—';return '<tr><td><b>'+E(r.buyer)+'</b><small>'+E(r.transaction||r.customerId||'')+'</small></td><td><b>#'+E(r.unit)+'</b><small>'+E(r.lockId||'')+'</small></td><td>'+E(r.channel==='ONLINE'?'Online':'Sales Center')+'</td><td><span class="p67g-badge '+(r.status==='EXTENSION_REQUESTED'?'warn':r.status==='EXTENDED_24H'?'ok':'')+'">'+E(String(r.status||'').replaceAll('_',' '))+'</span></td><td><b class="p67g-time" style="font-size:10px!important" data-p67g-inbox="'+E(r.id)+'">'+clock(left(r))+'</b></td><td>'+E(r.request&&r.request.reason||'—')+'</td><td><div class="p67g-actions" style="margin:0">'+actions+'</div></td></tr>'}).join('')+'</table></div></section></div>'}
  ['t-inbox','t-readiness'].forEach(function(id){var p=P[id];if(!p||typeof p.render!=='function'||p.render.__p67Inbox)return;var base=p.render;var fn=function(){return inbox()+String(base())};fn.__p67Inbox=true;p.render=fn});
  if(!window.__PRENEURA67_INBOX_TIMER)window.__PRENEURA67_INBOX_TIMER=setInterval(function(){document.querySelectorAll('[data-p67g-inbox]').forEach(function(el){var r=rec(el.dataset.p67gInbox);if(r)el.textContent=clock(left(r))})},1000);
})();
